- frontend/src/pages/index.tsx
Change scaling of containers on front page.
_Explain why this was implemented._
Using tailwind.
_What is the benefit of this PR?_
Accessibility for other various sizes.
> Tune styling

- backend/webserver/src/domain/code_runner_result.rs
- backend/webserver/src/endpoints/haskell.rs
- backend/webserver/src/services/code_runner.rs
Handling compilation errors and including the compilation error in the response.
So the client knows that their code does not compile.
Compilation error handling and better UX.
> Compilation error handling

- backend/webserver/Cargo.lock
- backend/webserver/Cargo.toml
- backend/webserver/src/domain/code_runner_result.rs
- backend/webserver/src/endpoints/haskell.rs
- backend/webserver/src/services/code_runner.rs
Handling code time out (i.e. making sure infinite loops do not cause the server to wait forever)
To ensure the server doesn't yield forever.
Handling code that never terminates or takes too long to execute (halting problem moment).
> Time out handling

- backend/webserver.readme.md
- backend/webserver/Dockerfile
- backend/webserver/readme.md
We were unable to deploy due to issues with memory and the ghc installation.
Use new commands to install and use run cmd to limit memory usage when building Rust app.
_What is the benefit of this PR?_
Deployable container for our code.
This resolves #38
> [OPS] Fix Dockerfile for GHC installation + deployment memory issues

- frontend/prisma/schema.prisma
Cascade delete _everything_ when parents are deleted.
Would you expect tests to remain when the problem was deleted? Not me.
> Cascade on delete

- frontend/src/pages/index.tsx
- frontend/src/server/router/problemRouter.ts
- frontend/src/server/router/problemSetRouter.ts
- frontend/src/server/router/syllabusRouter.ts
Removed schema validation for outputs and added type annotations so tRPC would pass the auto-generated Prisma model types.
Typesafety!
> Typesafety for queries

- report/sections/Chapter 1/Intro.tex
- report/sections/Chapter 1/MVP.tex
- report/sections/Chapter 1/problem_analysis.tex
Corrections from supervisor feedback.
Stuff was wrong - still is, though, less wrong.
We probably need to rewrite the whole problem analysis...
> Corrections 15/10

- backend/webserver/Cargo.lock
- backend/webserver/Cargo.toml
- backend/webserver/src/endpoints/haskell.rs
- backend/webserver/src/main.rs
- backend/webserver/src/services/code_runner.rs
- backend/webserver/src/services/mod.rs
- backend/webserver/src/services/test_runner.rs
- frontend/src/pages/test.tsx
- frontend/src/server/router/code.ts
Added a route to spam the backend with code.
1k reqs: 101360 ms
100 reqs: 8849 ms
10 reqs: 1135 ms
1 req: 337 ms
> Spam router for load testing

- frontend/prisma/schema.prisma
- frontend/src/server/router/problemRouter.ts
- frontend/src/server/router/problemSetRouter.ts
- frontend/src/server/router/syllabusRouter.ts
- frontend/src/server/router/testRouter.ts
We added the ability to post Problems, problemSets and syllabi
It was implemented using TRPC
We can now post stuff
> Trpc post request

- frontend/package.json
- frontend/prisma/schema.prisma
Environment file to implement connection to PostGres.
1. Install postgres on computer
2. In frontend use `npm run db:push`
3. Use postman and send a get request to `localhost:3000/api/addtestdata`
We now use postgres instead of sqlite so we have actual persistence.
Changed .env file located on discord
> Getting .schema postgres ready

- frontend/src/server/router/code.ts
Added support for new backend API.
Two requests and lots of retries.
> Use new backend api

- frontend/src/components/navbar.tsx
Added a menu that allows users to sign out.
With headless UI & Next-Auth.
Highly demanded feature from @TheRumle. [One must imagine him happy logging in and signing out](https://www.davelabowitz.com/wp-content/uploads/Sisyphus-e1557869810488.jpg).
> Add log out btn

- frontend/src/pages/problem/[problemId]/index.tsx
The submit button for problems now get disabled while waiting for a response.
TRPC / React Query.
Unintentional spam is now a thing of the past
> disable submit in submit loading state

- backend/webserver/src/debug.rs
- backend/webserver/src/main.rs
- backend/webserver/src/services/test_runner.rs
- backend/webserver/src/services/worker.rs
Webserver only logs in debug mode now and not in release mode.
Using a macro for conditional compilation.
Better performance.
> Log debug information in debug mode only

- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
- report/sections/Chapter 06 - Test runner/Chapter 6.tex
> Test runner deepdive

- report/bib/mybib.bib
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
Added usability testing section.
> add usability testing section in preliminaries

- report/bib/mybib.bib
- report/sections/Chapter 01 - Introduction/Intro.tex
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
- report/sections/Chapter 03 - Speecification/Specification.tex
Text describing preliminaries for benchmarking.
This gives us correct terminology and reasoning when describing benchmark code later.
> Benchmark prelim and spec. adjustment

- report/sections/Chapter 01 - Introduction/Intro.tex
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
> commit suggestions from code review

- report/sections/Chapter 06 - Test runner/Chapter 6.tex
Ending off the section and natural progression into queue system.
Using vim and Colemak.
A better test runner section.
> Test runner section ending

- report/sections/Chapter 01 - Introduction/Intro.tex
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
- report/sections/Chapter 07.5 - Benchmarking/Chapter 7.5.tex
Text for how we perform stress test.
> Benchmarking dd

- report/bib/mybib.bib
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
- report/sections/Chapter 07 - Queue System/Chapter 7.tex
Introduced Cargo, Tokio, axum and Rocket
yea
Citations and stuff
> Introduce Cargo, Tokio, axum and Rocket

- report/sections/Chapter 09 - Evaluation/UI evaluation.tex
> UI evaluation

- report/sections/Chapter 06 - Test runner/Chapter 6.tex
Rocket to axum explanation.
Word by word.
Rocket to axum explanation paragraph.
> Rocket to axum explanation

- report/bib/mybib.bib
- report/sections/Chapter 02 - Preliminaries/preliminaries.tex
- report/sections/Chapter 09 - Evaluation/UI evaluation.tex
A UI Evaluation results section
An UI Evaluation was conducted with other students from the semester and the results was then calculated
We now know that we have a good UI according to its SUS score
> UI eval results

- benchmarks/Benchmarks/RocketBenchmarks.cs
- benchmarks/Clients/CodeRunnerClient.cs
> Hardcode things

- report/sections/Preliminaries/preliminaries.tex
> Chapter 2 corrections

- report/sections/Appendix/frontend-images.tex
- report/sections/Frontend/chapter.tex
- report/sections/Frontend/client-server-interaction.tex
There are many big rewrites that we have not done as it would need to be moved somewhere else
> carlos comments for chapter 6

- report/sections/Frontend/chapter.tex
- report/sections/Specification/Specification.tex
carlos corrections + fix an error
> carlos corrections + fix error

- report/sections/Preliminaries/preliminaries.tex
> Chapter 2 corrections carlos

- report/sections/Preliminaries/preliminaries.tex
> Chapter 2 fixes
